#Trabajo supervisado de introducción de programación, 7/09/2023, Angie López
print("Mi segundo programa")
print("Ingrese su nombre: ")
Nombre = input()
print(Nombre)
print("Ingrese su edad: ")
Edad = input()
print(Edad)
print("Ingrese su carrera: ")
Carrera = input()
print(Carrera)
print("Ingrese su carne: ")
Carne = input()
print(Carne)

print("Soy " + Nombre , end="")
print(", tengo " + Edad,  end="")
print(" años y estudio la carrera de " + Carrera,  end="")
print(". Mi número de carne es " + Carne,  end="")